### PR TITLE
Merge gip-13 branch into main

### PR DESCRIPTION
**Pull request by nenadV91**
- merge `gip-13` branch
- remove Rinkeby data

### CODE REVIEW

**Review by alfetopito — COMMENTED** [review]
Will the Goerli mappings come in another PR?

I see references to it in the README but I cannot see any folder for Goerli being added

**Comment by nenadV91** [comment]
Goerli mappings are already merged in main branch, this PR just merges mainet and gc mappings from `gip-13` branch because on that branch those folders have latest updates. And this PR also removes Rinkeby
Screenshot from 2022-10-28 12-53-01

**Comment by nenadV91** [comment]
Btw I tested it with one of the demo accounts and it seems to be working 
Screenshot from 2022-10-28 12-55-21

**Review by fedgiac — APPROVED** [review]
> Will the Goerli mappings come in another PR?

The Görli mapping is the same as the one currently availabe on `main`. :heavy_check_mark:

**Review by anxolin — APPROVED** [review]

**Pull request merged**
